fade_on:
  name: Fade on
  description: Fade to a target volume level over time.
  target:
    entity:
      integration: snooz
      domain: fan
  fields:
    duration:
      name: Fade duration
      description: Time it takes to reach the target volume level.
      selector:
        number:
          min: 1
          max: 300
          unit_of_measurement: seconds
          mode: box
    volume:
      name: Target volume
      description: If not specified, the volume level is read from the device.
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

fade_off:
  name: Fade off
  description: Fade volume off over time.
  target:
    entity:
      integration: snooz
      domain: fan
  fields:
    duration:
      name: Fade duration
      description: Time it takes to turn off.
      selector:
        number:
          min: 1
          max: 300
          unit_of_measurement: seconds
          mode: box
