transition_on:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: snooz
    duration:
      default: 20
      selector:
        number:
          min: 1
          max: 300
          unit_of_measurement: seconds
          mode: box
    volume:
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    fan_speed:
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

transition_off:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: snooz
    duration:
      default: 20
      selector:
        number:
          min: 1
          max: 300
          unit_of_measurement: seconds
          mode: box
    volume:
      selector:
        constant:
          label: Enabled
          value: true
    fan_speed:
      selector:
        constant:
          label: Enabled
          value: true
